stages:
  - build
  - upload
  - release

variables:
  WINDOWS_STORMLIB_X64: "windows-stormlib-x64-latest"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/stormlib/latest"

build:
  stage: build
  image: archlinux:latest
  script:
    - echo 'creating release'
    - pacman -Sy
    - pacman -S --noconfirm zip
    - zip -r ${WINDOWS_STORMLIB_X64}.zip stormlib
  artifacts:
    paths:
      - ${WINDOWS_STORMLIB_X64}.zip
upload:
  stage: upload
  image: python:latest
  script:
    - pip3 install requests
    - python upload-package.py ${CI_API_V4_URL} ${CI_JOB_TOKEN} ${CI_PROJECT_ID} ${WINDOWS_STORMLIB_X64}
    #- |
    #  'PROJECT_ID' = "$"
    #  curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "${PACKAGE_REGISTRY_URL}/projects/${CI_PROJECT_ID}/packages"
    #  curl --request DELETE --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "${PACKAGE_REGISTRY_URL}/projects/${CI_PROJECT_ID}/packages/:package_id"
    #  curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${WINDOWS_STORMLIB_X64}.zip "${PACKAGE_REGISTRY_URL}/${WINDOWS_STORMLIB_X64}.zip"
    #  curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/latest"



    
release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Release latest" --tag-name latest \
        --assets-link "{\"name\":\"${WINDOWS_STORMLIB_X64}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${WINDOWS_STORMLIB_X64}\"}" 
  