stages:
  - build
  - upload
  - release

variables:
  WINDOWS_STORMLIB_X64: "windows-stormlib-x64-latest"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/stormlib/latest"

build:
  stage: build
  image: archlinux:latest
  script:
    - echo 'creating release'
    - zip -r ${WINDOWS_STORMLIB_X64}.zip stormlib
  artifacts:
    paths:
      - ${WINDOWS_STORMLIB_X64}.zip
upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file stormlib/ "${PACKAGE_REGISTRY_URL}/${WINDOWS_STORMLIB_X64}"

release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Release latest" --tag-name latest \
        --assets-link "{\"name\":\"${DARWIN_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${WINDOWS_STORMLIB_X64}\"}" 